### ISSUE TITLE
For example, you do not work, please help

### ISSUE THREAD

**Issue by Rasool-deldar** [innocenzi/laravel-inertia-vite-test#1]
I have installed the package and I am running, but the white screen shows that I am running with vite, giving a 404 error.

![image](https://user-images.githubusercontent.com/58503211/115107692-bd45d500-9f81-11eb-88ac-ba866dbbef88.png)
![image](https://user-images.githubusercontent.com/58503211/115107695-c33bb600-9f81-11eb-93b6-1df706e21ded.png)

**Comment by innocenzi** [comment]
Hello, Vite's development server only serves assets. In order to access your app, you need to use a web server like Valet or `php artisan serve`.
